language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "rg5pgFl5dOoJ5xpJotlQLctzcGY+wIh7OM90E36sAbJIw5b6Id/2iI8BOJunG+vEWxScKDT5MYIV7AxTcd/um6bLNjfoiykUhIQjuNRJwH5MFxqwRX8Fl0VgD1NTodPJmqF/6xVjtqo+Tkb6jheV/Neurprz8+UPpa1QXvEEejfYvD/QYd5yybdGVvmZof130TAk2PkTJ8W27Wyo1DjhAnp+yA7BqO2iN0zlE1fhN566/fn6KiQR3FXRQaQY+/ANZ3+vIDhIeJT23VXfzCv9d/XX4F+71sVjzzQlsD5jUR7UTXTnbbSfHBYXqTZ3M/AaWeLzAgoMVJGgq/woqqcSl+q9mhdSQyD7jpJfdjCn8fo04nM+oqdVUGpd+MM9GZVjHeW6KVpMwHOcY69B+J6I6lJNxrar2De/NfI3vYvFTA7+SIJm3QJORCLJqnYRjlzVjE/1gu/sOAl6f30nJA+L8EFsU9FTdb6emV8Sdp/IoKS+N63jJlcyWCnlmR5EK2AbJlvA7qn0yLmLl39OWtyXqGF/SWpnmGOM6VytXTWhmoN63AFkjVIvnjpWBVNuJPH3FmesfRkivd+O1aECBaqMmVq65cwuOlyTdqQ6t+eif/bChBafbzGH8jbgB/rlMNSnksEp8+/F9wWwvjiYsi+/xJv/rZ/bQ+880XRS9cbwops="
  - secure: "lPbHxGGKGswRl0hb4b3vKP1zy4OqX71QaQOekha6tZohAg5dz9O8QhiZv7AjTKxJ3TO1KuJHdnF9woj4xibYPE/2MAVuDdtBL3aCSyPoBIEb3C7Clz0iN4PF9vhWBKsaX8HU2D+nePyr9N6N3txR2gLH7oloNlhlVTK1TGkTJRPhcNbL1pC3WDEHhYkaQyM5jK7YekCbD+NVXG2L3pazyaLoTNdXgao55EvgihbX5G6ataT/5/tCJolm39jJ19IIOog1BYG3/r7G5ZPqrS08vbEjf0GK4z88wq87zLZOyiksSRjYr6TbWzlqKTfCsQZXAfpbxQg3V4OZY4q1MKDH1F8dizeNGtGWiJFwmr5seAtqXAxKyfmya24eWG8mUiRZ+NztuPlKOGCW+rmH1riGxxJq9bfUw0sy8SPjKhqkL2PqGo9LZG/Fl5WH3IY2xFB61FeJinItVXu0aCCnN/ltQNmxPyw8RKD/iIa5NMpoSoz2ystn+yXGnr1wJX8LVjo2oz76j8yd064bw4DVtbP0Q2hL3hHZevF4qYo6Wj5rLXvEfD0cZzzLj3pNlUS6LqjgionTLcU0MrjIP4flpZq6vWN5yBqqqxfYBhbY/azYmyrS10QgOHdkLWnUyu+hjzs7KwKo93qkSyJQNNI8BHTL+ehG7ReQ/nAHUHpzxxjKQ7M="
  - secure: "nAJICnuadw+ePclDVLctcMSbU3j38r+v0+tMCiVDZH8tJ/T4UNnY0i9gXGtZMLoOtWGwJkTTaUppEKzUmtedgzQ3fIgn9Wif486/C2BF6OF4xwRrpDIhbyRP9ghcTqqNxaSUIUsDgssHLekCsDzqG4kfaXC4Ha8owFHLH6WF+gGrty1lTLrc7lpZPFr+IuzwgnDsYtyttR7ojA6rUyvuDYKYCNuS5xGk8l0owMiGNRO5qpVPZS7rEKT8UCOMxf2dop5hlsVjz6idEksuZ1fE2lLVJhoGTXaq1A6JMrwaSoVynQPd/jLaZYwwGCmYsIc/pkOByVBgWPkP3yx6Bfws3LAFlmdsQwnwQl+D/phRk25lm+us8A1H+/n9dE9E+Z6oUGc7Woc+UV3pMbLFrQeNMeyt38EXaLdVdaLoSDJRH27kuS4TjRQMajoaCG56BnKnivZnk22ZHeI4Sq+KoRx5MLgkep0P2xolSmzzO9KIsJMuTzy362/Z2PbjH66Ylw5iOyOHeoM2vHi6SNpRaVBBFq9Zsv3T5ZHwnSZSSpywpCoXfm4c9wQSJYHc3KLvQtj0V7j+3dUo7oACEsXnR/EsxKYg3Jb/ac/iGw8M1Rt4HH4YW6QloSXefzf3jE1qti2fE0JmXgCrWblKssIYgWuqZh420U7bhXVdB/ad9QJq8MU="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_7fce683eeace_key -iv $encrypted_7fce683eeace_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi